root: true

env:
  node: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:prettier/recommended

plugins:
  - import

parserOptions:
  parser: "@typescript-eslint/parser"
  project:
    - "./tsconfig.eslint.json"

ignorePatterns:
  - dist/

rules:
  "@typescript-eslint/ban-ts-comment":
    - off

  "@typescript-eslint/explicit-function-return-type":
    - warn
    - allowTypedFunctionExpressions: true

  "@typescript-eslint/naming-convention":
    - warn
    - selector: default
      format:
        - camelCase

    - selector:
        - variable
      format:
        - camelCase
        - PascalCase
        - UPPER_CASE

    - selector: parameter
      format:
        - camelCase
        - PascalCase
      leadingUnderscore: allow

    - selector: property
      format:
        - camelCase
        - PascalCase
        - UPPER_CASE

    - selector: import
      format:
        - PascalCase
        - camelCase

    - selector: typeLike
      format:
        - PascalCase

  "@typescript-eslint/no-explicit-any":
    - warn
    - ignoreRestArgs: true

  "@typescript-eslint/no-non-null-assertion":
    - off

  "@typescript-eslint/no-unsafe-member-access":
    - warn

  curly:
    - error
    - multi
    - consistent

  eqeqeq: error

  import/consistent-type-specifier-style:
    - error
    - prefer-top-level

  import/dynamic-import-chunkname:
    - error

  import/first:
    - error

  import/newline-after-import:
    - error

  import/no-commonjs:
    - error

  import/no-cycle:
    - error

  import/no-duplicates:
    - error
    - considerQueryString: true

  import/no-named-default:
    - error

  import/no-restricted-paths:
    - error
    - zones:
        - target: packages/*/src/client/**
          from: packages/*/src/node/**
        - target: packages/*/src/node/**
          from: packages/*/src/client/**

  import/order:
    - error
    - alphabetize:
        order: asc
        orderImportKind: asc
      groups:
        - builtin
        - external
        - internal
        - - parent
          - sibling
        - index
        - object
      newlines-between: always

  line-comment-position: error

  no-duplicate-imports:
    - off

  no-unmodified-loop-condition:
    - error

  object-shorthand: error

  padding-line-between-statements:
    - error
    - blankLine: always
      prev:
        - const
        - let
      next:
        - "*"
    - blankLine: any
      prev:
        - const
        - let
      next:
        - const
        - let
    - blankLine: always
      prev:
        - "*"
      next:
        - return

  prefer-destructuring:
    - error
    - object: true

  prefer-template: error

overrides:
  - files:
      - "*.d.ts"
    rules:
      no-underscore-dangle:
        - off

  - files:
      - "**/__tests__/**/*.spec.{j,t}s?(x)"

    rules:
      "@typescript-eslint/no-explicit-any":
        - off
      "@typescript-eslint/no-unsafe-call":
        - off
      "@typescript-eslint/no-unsafe-assignment":
        - off
      "@typescript-eslint/no-unsafe-member-access":
        - off
      import/dynamic-import-chunkname:
        - off
