allowBuilds:
  "@parcel/watcher": true
  es5-ext: true

configDependencies:
  pacquet: ^0.11.12

enableGlobalVirtualStore: true

minimumReleaseAgeExclude:
  - "@oxfmt/*"
  - "@oxlint/*"
  - oxc-config-hope
  - oxfmt
  - oxlint

packageExtensions:
  "@codecov/rollup-plugin":
    peerDependenciesMeta:
      rollup:
        optional: true

  conventional-changelog-preset-loader:
    peerDependencies:
      conventional-changelog-conventionalcommits: ^10.0.0
    peerDependenciesMeta:
      "conventional-changelog-core":
        optional: true

trustPolicyExclude:
  # node types
  - undici-types@6.21.0
